### ISSUE TITLE
No .hdarc file in $HOME

### ISSUE THREAD

**Issue by an-nicolas** [ecmwf/hda#11]
I am trying to download images with the jupyter notebook tool. 
At the configuration step of API authentification I am supposed to check the existance of the .hdarc file with 
`find $HOME -type f -name .hdarc`

The file doesn't exist and I have no idea how to create it or how I can access the $HOME directory. 
Can you explain how to do that please ?

**Comment by nisc586** [comment]
Hi,

To be able to download data you have to register with Wekeo.
The .hdarc file is just a text file where you store the url of the API, your username ,and your password. You can create that file yourself. For me it looks like this:
```
 url: https://wekeo-broker-k8s.apps.mercator.dpi.wekeo.eu/databroker 
 user: my_username
 password: my_password
```

$HOME refers to an environment variable on your machine. It depends on your computer what the $HOME direcotry actually is. Usually it is something like C:/Users/my_username/.

I hope this helps.
