### ISSUE TITLE
Expected download size should be taken from http server header, rather than catalog metadata

### ISSUE THREAD

**Issue by jgc31** [ecmwf/hda#3]
Dear HDA Python Library Author,

First, thank you very much for this very nice library.

I work at WEkEO Helpdesk (first level of WEkEO User Support Service), and I am reporting a potential bug, that causes a user trying to download High Resolution Snow and Ice dataset with the HDA Python library to get an error. 
This dataset is zipped on the fly for download purpose, and its metadata size slightly differs from the product size (zip version) once downloaded.

In an exchange with the data producer, he argued that:

> “But please consider passing the file size that can obtained from the header for the automatic library checks. In the example below with curl we clearly see that the expected value is correct in the header. Using the value provided as information directly in the catalogue product metadata is not reliable and should not be used for that purpose.”

which seems to make sense. So I am informing you about this issue.

I am attaching a file that includes a detailed log of debugging output when trying to use the HDA Python Library to download an HR-S&I dataset, and some of our ensuing internal discussion.

Many thanks in advance for your help.

Kind regards,
Jean-Guilhem Cailton
The WEkEO Helpdesk

[HDA-Python-Library-expected-size-issue-with-zipper.md](https://github.com/ecmwf/hda/files/7242905/HDA-Python-Library-expected-size-issue-with-zipper.md)

**Comment by jgc31** [comment]
… and here is the content of the fsc2.json file used as input for debugging, and mentioned in the file attached above:

>{
"datasetId": "EO:CRYO:DAT:HRSI:FSC",
"boundingBoxValues": [ {
"name": "bbox",
"bbox": [
10.6285389477305539,
46.5472809501866692,
11.1393330751609078,
46.8963787479057274
]
}
],
"dateRangeSelectValues": [ {
"name": "Observed",
"start": "2021-07-30T00:00:00.000Z",
"end": "2021-08-01T00:00:00.000Z"
}, {
"name": "Published",
"start": "2017-07-01T00:00:00.000Z",
"end": "2021-08-02T00:00:00.000Z"
}
],
"stringChoiceValues": [ {
"name": "productType",
"value": "FSC"
}
]
}

**Comment by jgc31** [comment]
The same issue also appears for Sentinel-3 OLCI products (that are also delivered as zipped files, from a different producer, EUMETSAT).
In this case, the downloaded size is slightly higher than the expected size, so the downloading succeeds, but it is followed by a warning message such as, for example:
"WARNING Oops, downloaded 726825725 byte(s), was supposed to be 726809968 (extra 15757)"
whereas the http headers contained the correct size:
"DEBUG Headers: {'Content-Length': '726825725', 'Accept-Ranges': 'bytes', 'Last-Modified': 'Fri, 01 Oct 2021 09:18:47 GMT', 'x-rgw-object-type': 'Normal', 'ETag': '"51edc5ec4f7ebc9b5aef2185b73b8c16"', 'x-amz-request-id': 'tx0000000000000046566f2-006156d27a-fa1170f-default', 'Content-Type': 'binary/octet-stream', 'Date': 'Fri, 01 Oct 2021 09:18:50 GMT'}"

I attach the debug log of downloading a couple of Sentinel-3 OLCI products:
[Sentinel-3-Oops.log](https://github.com/ecmwf/hda/files/7265975/Sentinel-3-Oops.log)

Note that Sentinel-3 queries must now include more mandatory parameters than in the example shown in the documentation (and succeed to find products only in the last year of the rolling archive). Here is for example the query for the above download log:
[Sentinel-3.json.txt](https://github.com/ecmwf/hda/files/7265992/Sentinel-3.json.txt)

**Comment by b8raoult** [comment]
At the time of the first version of the package, the server did not return the Content-Length, so we had to rely on the (often incorrect) size in the catalogue. Please bear in mind that if the Content-Encoding header is set, the Content-Length refers to the encoded size.
